STOCKS = ["RELIANCE.NS", "TCS.NS", "HDFCBANK.NS"]
SHEET_NAME = "AlgoTradingLog"

TELEGRAM_TOKEN = "REPLACE_YOUR_TOKEN"

TELEGRAM_CHAT_ID = "1676503822" # REPLACE by YOUR CHAT ID

SHEET_EMAIL = "REPLACE BY YOUR GOOGLE CLOUD CONSOLE SERVICE ACCOUNT API EMAIL PROVIDED TO YOU" # this is NOT general email (abc@gmail.com)

TICKERS = ["INFY.NS","RELIANCE.NS","TATAPOWER.NS"]
